export const tinyMCEConfig = {
  height: 600,
  menubar: true,
  plugins: [
    "advlist",
    "autolink",
    "lists",
    "link",
    "image",
    "charmap",
    "preview",
    "anchor",
    "searchreplace",
    "visualblocks",
    "code",
    "fullscreen",
    "insertdatetime",
    "media",
    "table",
    "help",
    "wordcount",
    "emoticons",
    "save",
    "autosave",
  ],
  toolbar:
    "undo redo | blocks | " +
    "bold italic forecolor backcolor | alignleft aligncenter " +
    "alignright alignjustify | bullist numlist outdent indent | " +
    "removeformat | link image media table | emoticons charmap | help",
  content_style:
    "body { font-family:Helvetica,Arial,sans-serif; font-size:14px }",
  branding: false,
  promotion: false,
  resize: true,
  statusbar: true,
  elementpath: true,
  paste_data_images: true,
  image_advtab: true,
  image_caption: true,
  zindex: 9999,
  table_appearance_options: true,
  media_live_embeds: true,
  contextmenu: "link image table",
  color_map: [
    "#BFEDD2",
    "Light Green",
    "#FBEEB8",
    "Light Yellow",
    "#F8CAC6",
    "Light Red",
    "#ECCAFA",
    "Light Purple",
    "#C2E0F4",
    "Light Blue",
    "#2DC26B",
    "Green",
    "#F1C40F",
    "Yellow",
    "#E03E2D",
    "Red",
    "#B96AD9",
    "Purple",
    "#3598DB",
    "Blue",
    "#169179",
    "Dark Turquoise",
    "#E67E23",
    "Orange",
    "#BA372A",
    "Dark Red",
    "#843FA1",
    "Dark Purple",
    "#236FA1",
    "Dark Blue",
    "#000000",
    "Black",
    "#525252",
    "Dark Gray",
    "#737373",
    "Gray",
    "#B3B3B3",
    "Light Gray",
    "#FFFFFF",
    "White",
  ],
  formats: {
    bold: { inline: "strong" },
    italic: { inline: "em" },
    underline: { inline: "u" },
    strikethrough: { inline: "strike" },
  },
  style_formats: [
    { title: "Başlık 1", block: "h1" },
    { title: "Başlık 2", block: "h2" },
    { title: "Başlık 3", block: "h3" },
    { title: "Başlık 4", block: "h4" },
    { title: "Başlık 5", block: "h5" },
    { title: "Başlık 6", block: "h6" },
    { title: "Paragraf", block: "p" },
    { title: "Alıntı", block: "blockquote" },
    { title: "Kod Bloğu", block: "pre" },
  ],
};
